# Generated by Django 4.0.4 on 2022-05-15 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amphitheatre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('numero', models.CharField(max_length=250)),
                ('capacite', models.TextField()),
                ('cout', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('details', models.TextField()),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('frais', models.IntegerField()),
                ('amphi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='conferences.amphitheatre')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('cin', models.CharField(max_length=20)),
                ('telephone', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='conferences_participants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='conferences.conference')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='conferences.participant')),
            ],
        ),
        migrations.AddField(
            model_name='conference',
            name='conferencier',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='conferencier', to='conferences.participant'),
        ),
        migrations.AddField(
            model_name='conference',
            name='participants',
            field=models.ManyToManyField(related_name='participants', through='conferences.conferences_participants', to='conferences.participant'),
        ),
    ]
