# Generated by Django 4.0.4 on 2022-05-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amphitheatre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('numero', models.IntegerField()),
                ('capacite', models.IntegerField()),
                ('cout', models.IntegerField()),
            ],
        ),
    ]
