# Generated by Django 4.0.4 on 2022-05-22 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('amphitheatres', '0001_initial'),
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=500)),
                ('details', models.TextField()),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('frais', models.IntegerField()),
                ('amphi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='amphitheatres.amphitheatre')),
                ('conferencier', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='conferencier', to='participants.participant')),
            ],
        ),
        migrations.CreateModel(
            name='conferences_participants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='conferences.conference')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='participants.participant')),
            ],
        ),
        migrations.AddField(
            model_name='conference',
            name='participants',
            field=models.ManyToManyField(related_name='participants', through='conferences.conferences_participants', to='participants.participant'),
        ),
    ]
